### ISSUE TITLE
挺好用的，可是为什么编译失败呢？

### ISSUE THREAD

**Issue by liyinfenggit** [HSunboy/dt-sql-parser#1]
npm run build的时候报的压缩js失败，请问什么原因啊，多谢。
ERROR in static/js/app.ef651fc99b3c386ce9a8.js from UglifyJs
Unexpected token: punc (,) [./node_modules/_dt-sql-parser@1.1.9@dt-sql-parser/index.js:5,0][static/js/app.ef651fc99b3c386ce9a8.js:1658,10]

**Comment by HSunboy** [comment]
UglifyJs需要支持ES6
