### ISSUE TITLE
有计划支持库表名和别名提示吗？

### ISSUE THREAD

**Issue by ayo4code** [HSunboy/dt-sql-parser#2]
rt

**Comment by ayo4code** [comment]
hsql 试了下是不支持的

**Comment by HSunboy** [comment]
> hsql 试了下是不支持的

不太清楚你所说的具体语法，最好提供一个语法格式或者例子

**Comment by ayo4code** [comment]
![image](https://user-images.githubusercontent.com/23436261/68388331-583a5d00-019b-11ea-8dd1-fdce56ed10a7.png)
类似这样的提示

**Comment by HSunboy** [comment]
表名识别是在from语句之后，需要在from后面加上表名才会出现table的提示
