### ISSUE TITLE
can it support xx.xxx.xxx as t1?

### ISSUE THREAD

**Issue by nixiaomei1205** [HSunboy/dt-sql-parser#4]
请问可以支持有两个层级的表名吗？比如database1.mode.tableName ，现在好像了如果这样会报错。非常感谢！

**Comment by HSunboy** [comment]
哪一种 SQL？

**Comment by nixiaomei1205** [comment]
sqlserver

**Comment by nixiaomei1205** [comment]
好像改成impala就可以了

**Comment by HSunboy** [comment]
普通的 sql 模式不支持 `database.schema.table` 的写法
Impala 目前是支持 database.table.field 的写法，可以暂时拿来弄一下
