### ISSUE TITLE
select from bishow.11 a333 where  表名带数字的好像不能识别别名

### ISSUE THREAD

**Issue by nixiaomei1205** [HSunboy/dt-sql-parser#6]
select from bishow.11 a333 where  表名带数字的好像不能识别别名，比如11,55，这时候a333就识别不出是别名，请问这个有办法解决吗？

**Comment by nixiaomei1205** [comment]
请问不能识别的情况是哪几种呢？

**Comment by HSunboy** [comment]
表名不能是纯数字。可以用  ` bishow.\`11\` `来代替

**Comment by nixiaomei1205** [comment]
收到！谢谢！
请问表名的规则是什么呢？不合法的表名有哪几种呢？

**Comment by HSunboy** [comment]
不同SQL不一样，具体的可以自己去查对应SQL的文档
