### ISSUE TITLE
有人吗

### ISSUE THREAD

**Issue by hulanyou** [HSunboy/dt-sql-parser#9]
**The Type of SQL**
e.g. Impala

**Your Code**
e.g. parser.parserSql(....);

**Problem**
e.g. the code do not work.

**Comment by HSunboy** [comment]
有人的

**Comment by hulanyou** [comment]
![微信图片_20200525184039](https://user-images.githubusercontent.com/30310014/82805951-735e8700-9eb7-11ea-9869-e739c0909928.jpg)
![微信图片_20200525184048](https://user-images.githubusercontent.com/30310014/82805954-73f71d80-9eb7-11ea-952a-7ce269122b48.jpg)

**Comment by hulanyou** [comment]
![aa](https://user-images.githubusercontent.com/30310014/82805999-85d8c080-9eb7-11ea-8bfa-08afbacba5f3.jpg)
![vvv](https://user-images.githubusercontent.com/30310014/82806002-8709ed80-9eb7-11ea-9c69-cb44025c46f6.jpg)

**Comment by hulanyou** [comment]
上传不了图片啊，方便加个联系方式吗

**Comment by hulanyou** [comment]
我import引入不了啊

**Comment by HSunboy** [comment]
webpack 是什么版本

**Comment by hulanyou** [comment]
内网环境就装了node，webpack好像没装

**Comment by HSunboy** [comment]
这个是项目编译工具不支持label写法，需要自己排查一下项目配置和工具

**Comment by hulanyou** [comment]
![8a561589f2286cc7626054d9b4f17f2](https://user-images.githubusercontent.com/30310014/82853637-d8a68c80-9f38-11ea-9129-8c4feb473813.jpg)
我直接用lib下的也是可以的吧
